### PR TITLE
Modify the welcome information to update the latest publishing trends

### PR DESCRIPTION
**Pull request by linyx233**
Modify the welcome information to update the latest publishing trends

### CODE REVIEW

**Comment by linyx233** [comment]
Hello, this is my first time to participate in the contribution document. I don't quite understand your feedback.Can you tell me how to submit PR specifically?

**Comment by imba-tjd** [comment]
@linyx233 不用管那个回复

**Comment by linyx233** [comment]
@imba-tjd thanks

**Comment by v-radelg** [comment]
Hello @linyx233  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by LisandroSu** [comment]
Hello, @<contributor's GITHUB name>,

Thank you for your feedback and suggestion. 
 
Unfortunately, we consider that the format was updated which is/are not fully aligned with our criteria for acceptance

Closing this PR since it does not apply

Thank you.

Kind regards,
 
Microsoft C&E Localization Team

**Pull request closed without merging**
