### PR TITLE
Fix：Some typo errors  in 'async.md'

### PR DESCRIPTION
**Pull request by Maledong**
1) "F##" should be "F#".
2) '.NET 可为应用和服务提供' lacked the object, fix this translation and make it better in native.

### CODE REVIEW

**Comment by Maledong** [comment]
Hi, 

I'm editing this file on Visual Studio Code and I'm using 'LF' as the normal new-line symbol, but why there're so many changes? In my VSC there's only one line changed:

image

**Comment by v-elcou** [comment]
Hello @Maledong, 
Thank for your contribution. We are currently reviewing and will communicate the decision taken. 
Thanks for your time and support on this.

Kind regards,
Microsoft C&E Localization Team

**Comment by ticianaciminari** [comment]
@Maledong:
Thank you for your contribution.
Your suggestions have been partially accepted. As I cannot edit the repo I will close the PR. But don't worry, we will include these suggestions into the next article update release. 
Thank you for your time and support.
Microsoft C&E Localization Team

**Comment by Maledong** [comment]
@ ticianaciminari：If you cannot help to edit the repo, please tell me if there's anything wrong and I'll try to fix and make force push. 

I wonder why the formation of "new-line" is mixed with windows (Ctrl+n) and Linux (\n)？

**Comment by Maledong** [comment]
@ticianaciminari：Now you can edit the file by re-opening it and then submit

PS：I wonder why there're too many mixed symbols of "new-lines"？

**Comment by imba-tjd** [comment]
> I'm editing this file on Visual Studio Code and I'm using 'LF' as the normal new-line symbol, but why there're so many changes? In my VSC there's only one line changed:

see https://github.com/dotnet/docs.zh-tw/issues/157

**Pull request closed without merging**
