### PR TITLE
Update lambda-expressions.md

### PR DESCRIPTION
**Pull request by as981242002**
Modify the translation error

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/lambda-expressions.md](https://github.com/as981242002/docs.zh-cn/blob/as981242002-patch-1/docs/csharp/lambda-expressions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet/csharp/lambda-expressions?branch=pr-zh-cn-48) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C2%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201709020520402957-48%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/lambda-expressions.md](https://github.com/as981242002/docs.zh-cn/blob/as981242002-patch-1/docs/csharp/lambda-expressions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet/csharp/lambda-expressions?branch=pr-zh-cn-48) |
[docs/csharp/language-reference/keywords/ref.md](https://github.com/as981242002/docs.zh-cn/blob/as981242002-patch-1/docs/csharp/language-reference/keywords/ref.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/ref?branch=pr-zh-cn-48) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C2%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201709020523507874-48%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @as981242002 , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @as981242002 

Some of the contributions were correct.

Please reopen this PR so we can implement them

Thanks for your support,
Microsoft C&E Localization Team

**Pull request closed without merging**
