### PR TITLE
Fix some error

### PR DESCRIPTION
**Pull request by imba-tjd**

### CODE REVIEW

**Comment by ChenDaqian** [comment]
我也是看到.NET CORE 和.NET 核心混用就很难受.

**Comment by imba-tjd** [comment]
@ChenDaqian your https://github.com/dotnet/docs.zh-cn/pull/182 is the subset of my commits...

**Comment by v-elcou** [comment]
@imba-tjd , Thank you for your feedback and suggestion! 
We are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@imba-tjd , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
