### PR TITLE
Migration Framework

### PR DESCRIPTION
**Pull request by Saisang**

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TOC.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/TOC.md) | :white_check_mark:Succeeded | |
[docs/framework/64-bit-apps.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/64-bit-apps.md) | :white_check_mark:Succeeded | |
[docs/framework/StructuredTOC.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/StructuredTOC.md) | :white_check_mark:Succeeded | |
[docs/framework/TOC.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/TOC.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/StructuredTOC.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/StructuredTOC.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/TOC.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/TOC.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/application-domains-and-assemblies-how-to-topics.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/application-domains-and-assemblies-how-to-topics.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/application-domains.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/application-domains.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assemblies-and-side-by-side-execution.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assemblies-and-side-by-side-execution.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assemblies-in-the-common-language-runtime.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assemblies-in-the-common-language-runtime.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assembly-contents.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assembly-contents.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assembly-location.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assembly-location.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assembly-manifest.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assembly-manifest.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assembly-names.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assembly-names.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assembly-placement.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assembly-placement.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assembly-security-considerations.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assembly-security-considerations.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/assembly-versioning.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/assembly-versioning.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/create-and-use-strong-named-assemblies.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/create-and-use-strong-named-assemblies.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/create-assemblies.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/create-assemblies.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/delay-sign-assembly.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/delay-sign-assembly.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/enhanced-strong-naming.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/enhanced-strong-naming.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/gac.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/gac.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-build-a-multifile-assembly.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-build-a-multifile-assembly.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-build-a-single-file-assembly.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-build-a-single-file-assembly.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-configure-an-application-domain.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-configure-an-application-domain.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-create-a-public-private-key-pair.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-create-a-public-private-key-pair.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-create-an-application-domain.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-create-an-application-domain.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-determine-assembly-fully-qualified-name.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-determine-assembly-fully-qualified-name.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-disable-the-strong-name-bypass-feature.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-disable-the-strong-name-bypass-feature.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-install-an-assembly-into-the-gac.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-install-an-assembly-into-the-gac.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-load-assemblies-into-an-application-domain.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-load-assemblies-into-an-application-domain.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-obtain-type-and-member-information-from-an-assembly.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-obtain-type-and-member-information-from-an-assembly.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-receive-first-chance-exception-notifications.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-receive-first-chance-exception-notifications.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-reference-a-strong-named-assembly.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-reference-a-strong-named-assembly.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-remove-an-assembly-from-the-gac.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-remove-an-assembly-from-the-gac.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-unload-an-application-domain.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-unload-an-application-domain.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-view-assembly-contents.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-view-assembly-contents.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/how-to-view-the-contents-of-the-gac.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/how-to-view-the-contents-of-the-gac.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/index.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/index.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/media/assemblyover1.gif](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/media/assemblyover1.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet-new/articles/framework/app-domains/media/assemblyover1.gif?branch=pr-zh-cn-21) |
[docs/framework/app-domains/media/assemblyover2.gif](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/media/assemblyover2.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet-new/articles/framework/app-domains/media/assemblyover2.gif?branch=pr-zh-cn-21) |
[docs/framework/app-domains/media/assemblytypes.gif](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/media/assemblytypes.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet-new/articles/framework/app-domains/media/assemblytypes.gif?branch=pr-zh-cn-21) |
[docs/framework/app-domains/media/versioningover.gif](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/media/versioningover.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet-new/articles/framework/app-domains/media/versioningover.gif?branch=pr-zh-cn-21) |
[docs/framework/app-domains/multifile-assemblies.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/multifile-assemblies.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/programming-with-assemblies.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/programming-with-assemblies.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/resolve-assembly-loads.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/resolve-assembly-loads.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/retrieve-setup-information.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/retrieve-setup-information.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/running-intranet-applications-in-full-trust.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/running-intranet-applications-in-full-trust.md) | :white_check_mark:Succeeded | |
[docs/framework/app-domains/set-assembly-attributes.md](https://github.com/dotnet/docs.zh-cn/blob/migration_framework/docs/framework/app-domains/set-assembly-attributes.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C16%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201704161518477742-21%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.IO.FileLoadException: Could not load file or assembly &#39;System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; or one of its dependencies. The located assembly&#39;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: &#39;System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; ---&gt; System.IO.FileLoadException: Could not load file or assembly &#39;System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; or one of its dependencies. The located assembly&#39;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: &#39;System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39;

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()



For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C17%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201704170830565364-21%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-cn, working directory: W:\zdab-s, target branch: master, target branch commit: d6029fb1097e425480261e5d5ae926d39b226111, source branch: migration_framework, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C21%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201704210414134059-21%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-cn, working directory: W:\4n1i-s, target branch: master, target branch commit: b045664f433eec5bd9438ede76ff8d44c3b3dcdd, source branch: migration_framework, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C24%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201704240313148815-21%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/dotnet/docs.zh-cn, working directory: W:\a1t5-s, target branch: master, target branch commit: b045664f433eec5bd9438ede76ff8d44c3b3dcdd, source branch: migration_framework, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C24%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201704240425019563-21%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Saisang** [comment]
close this because this is merged into master-oldev already.

**Pull request closed without merging**
