### PR TITLE
fix typo.  有点 -> 优点

### PR DESCRIPTION
**Pull request by wangyanjun**

### CODE REVIEW

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/deploying/index.md](https://github.com/wangyanjun/docs.zh-cn/blob/master/docs/core/deploying/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-cn/dotnet-new/articles/core/deploying/index?branch=pr-zh-cn-24) | [Details](#user-content-docs%2Fcore%2Fdeploying%2Findex.md)

<a name="docs%2Fcore%2Fdeploying%2Findex.md"></a>
### [docs/core/deploying/index.md](https://github.com/wangyanjun/docs.zh-cn/blob/master/docs/core/deploying/index.md)
 - **Line 69**: **[Warning]** Invalid file link:(~/docs/core/deploying/deploy-with-cli.md).
 - **Line 69**: **[Warning]** Invalid file link:(~/docs/core/deploying/deploy-with-vs.md).
 - **Line 79**: **[Warning]** Invalid file link:(~/docs/core/deploying/deploy-with-cli.md).
 - **Line 80**: **[Warning]** Invalid file link:(~/docs/core/deploying/deploy-with-vs.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C2%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201705021626096588-24%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @wangyanjun , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@wangyanjun , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/deploying/index.md](https://github.com/wangyanjun/docs.zh-cn/blob/master/docs/core/deploying/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-cn/dotnet-new/articles/core/deploying/index?branch=pr-zh-cn-24) | [Details](#user-content-docs%2Fcore%2Fdeploying%2Findex.md)

<a name="docs%2Fcore%2Fdeploying%2Findex.md"></a>
### [docs/core/deploying/index.md](https://github.com/wangyanjun/docs.zh-cn/blob/master/docs/core/deploying/index.md)
 - **Line 71**: **[Warning]** Invalid file link:(~/docs/core/deploying/deploy-with-cli.md).
 - **Line 71**: **[Warning]** Invalid file link:(~/docs/core/deploying/deploy-with-vs.md).
 - **Line 81**: **[Warning]** Invalid file link:(~/docs/core/deploying/deploy-with-cli.md).
 - **Line 82**: **[Warning]** Invalid file link:(~/docs/core/deploying/deploy-with-vs.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C8%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201705081702244762-24%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
