### PR TITLE
fix keyword index

### PR DESCRIPTION
**Pull request by ZSkycat**
1. keyword 不应该翻译
2. 去掉不符合中文习惯的"。"后面的空格

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/language-reference/keywords/index.md](https://github.com/ZSkycat/docs.zh-cn/blob/fix_keyword/docs/csharp/language-reference/keywords/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/index?branch=pr-zh-cn-47) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C30%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201708301119251243-47%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
尊敬的 @ZSkycat ：你好！我们仍在讨论中，稍后很快就会通知你我们的决定。 
  
谢谢你的支持！
Microsoft C&E 本地化团队敬上

**Comment by gosali** [comment]
@mairaw, Could you please change the base branch for this PR?
Thank you in advance!

**Comment by mairaw** [comment]
done @gosali!

**Comment by ZSkycat** [comment]
@mairaw yes, I am wrong to submit to 'master' on the first. What can I do to help you?

**Comment by mairaw** [comment]
No worries @ZSkycat. I've removed the other commits now. Now the localization team should get back to you on this. Thanks!

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/language-reference/keywords/index.md](https://github.com/ZSkycat/docs.zh-cn/blob/fix_keyword/docs/csharp/language-reference/keywords/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/index?branch=pr-zh-cn-47) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C31%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201708310528197295-47%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
@ZSkycat  : Thank you for your feedback and suggestion! 
  
The feedback is considered. We will tune part of  your feedbacks in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
  
Microsoft C&E Localization Team

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/language-reference/keywords/index.md](https://github.com/ZSkycat/docs.zh-cn/blob/fix_keyword/docs/csharp/language-reference/keywords/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/index?branch=pr-zh-cn-47) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C6%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201709061721486465-47%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
