### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by alexjuv**
a little correction on translation

### CODE REVIEW

**Comment by alexjuv** [comment]
translation correting

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/index.md](https://github.com/alexjuv/docs.zh-cn/blob/patch-1/docs/core/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/zh-cn/dotnet-new/articles/core/index?branch=pr-zh-cn-27) | [Details](#user-content-docs%2Fcore%2Findex.md)

<a name="docs%2Fcore%2Findex.md"></a>
### [docs/core/index.md](https://github.com/alexjuv/docs.zh-cn/blob/patch-1/docs/core/index.md)
 - **Line 30**: **[Warning]** Invalid file link:(~/docs/standard/library.md).
 - **Line 51**: **[Warning]** Invalid file link:(~/docs/standard/library.md).
 - **Line 57**: **[Warning]** Invalid file link:(~/docs/standard/library.md).
 - **Line 115**: **[Warning]** Invalid file link:(~/docs/images/corefx-platforms-loc.png).
 - **Line 137**: **[Warning]** Invalid file link:(~/docs/standard/library.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C12%5C503d5969-5221-e462-4715-7f911c8e603a%5CPullRequest%5C201705120828572106-27%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by CeciAc** [comment]
Hi **@alexjuv**  we are still in discussing, will update the decision later soon. 
_Thanks for your support,
Microsoft C&E Localization Team_

**Comment by v-radelg** [comment]
@alexjuv , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
